#!/bin/sh

__httpcode=`cat ${AE_HTTPCODE}`
__httpfirst=`echo $__httpcode | sed s'+^\(.\).*$+\1+'`
if [ "$__httpfirst" = "4" ]; then
    fail "$__httpcode : ${AE_RESPONSE}"
fi
if [ "$__httpcode" = "000" ]; then
    fail "looks like the server is not up... : $__httpcode : ${AE_RESPONSE}"
fi
