#!/bin/sh
__=
if [ "${AE_METHOD}" = "POST" ]; then
    checkopts $# 3 'login email password' $4
    jsonadd "login" $1
    jsonadd "email" $2
    jsonadd "password" $3
    if [ $# = 4 ]; then jsonmerge $__ $4; fi
    AE_REQUEST=$__
fi
if [ "${AE_METHOD}" = "PUT" ]; then
    checkopts $# 3 'login' $4
    jsonadd "login" $1
    jsonadd "email" $2
    jsonadd "publicize" $3
    if [ $# = 4 ]; then jsonmerge $__ $4; fi
    AE_REQUEST=$__
fi
if [ "${AE_METHOD}" = "GET" -o "${AE_METHOD}" = "DELETE" -o ${AE_METHOD} = "PUT" ]; then
    __userkey=$1
    AE_RESOURCE=${AE_RESOURCE}/${__userkey}
fi

