#!/bin/sh -e

  status r

    user c postmarkapp info@postmarkapp.com orange                            '{"publicize":"true","name":"Post_Mark_Bod","url":"http://postmarkapp.com/"}'

     api c postmarkapp Post_Mark false                                        '{"version":{"baseurl":"http://api.postmarkapp.com/","label":"1.0","index":"POSTMARK_API"}}'

resource c postmarkapp Post_Mark 1 /email                      Status         '{"tag":"#email","description":"emailing"}'
  method c postmarkapp Post_Mark 1 /email                      POST   Create

representation c postmarkapp Post_Mark 1 '{"name":"email_body","representation":{"type":"object","attributes":[{"name":"From","description":"_desc_","type":"string"},{"name":"To","description":"_desc_","type":"string"},{"name":"Subject","description":"_desc_","type":"string"},{"name":"TextBody","description":"_desc_","type":"string"}]}}'

