#!/bin/sh -e

  status r

    user c cog cog@apiengine.io orange                                                                                             '{"publicize":"true","name":"The_Big_Cog","url":"http://apiengine.io/spinning/cogs"}'

     api c cog Api_Engine false                                                                                                    '{"version":{"baseurl":"http://apiengine.io/cog/","label":"0.7","index":"some_markdown_for_v0.7"}}'

resource c cog Api_Engine 1 /status                                                                             Status             '{"tag":"#status","description":"general_system_status"}'
  method c cog Api_Engine 1 /status                                                                             GET      Read

resource c cog Api_Engine 1 /session                                                                            Session            '{"tag":"#session,#login","description":"login_and_system_management"}'
  method c cog Api_Engine 1 /session                                                                            POST     Create
  method c cog Api_Engine 1 /session                                                                            GET      Read
resource c cog Api_Engine 1 /session/{session}                                                                  Session            '{"tag":"#session,#login","description":"login_and_system_management"}'
  method c cog Api_Engine 1 /session/{session}                                                                  DELETE   Delete

resource c cog Api_Engine 1 /user                                                                               User               '{"tag":"#user","description":"user_management"}'
  method c cog Api_Engine 1 /user                                                                               POST     Create
  method c cog Api_Engine 1 /user                                                                               GET      Read
resource c cog Api_Engine 1 /user/{user}                                                                        User               '{"tag":"#user","description":"user_management"}'
  method c cog Api_Engine 1 /user/{user}                                                                        GET      Read
  method c cog Api_Engine 1 /user/{user}                                                                        UPDATE   Update
  method c cog Api_Engine 1 /user/{user}                                                                        DELETE   Delete

resource c cog Api_Engine 1 /passwordreset                                                                      Password           '{"tag":"#password,#login","description":"password_reset"}'
  method c cog Api_Engine 1 /passwordreset                                                                      POST     Create
resource c cog Api_Engine 1 /passwordreset/{token}                                                              Credentials        '{"tag":"#password,#login","description":"password_reset"}'
  method c cog Api_Engine 1 /passwordreset/{token}                                                              POST     Create
  method c cog Api_Engine 1 /passwordreset/{token}                                                              GET      Read

resource c cog Api_Engine 1 /api                                                                                Api                '{"tag":"#api","description":"apis"}'
  method c cog Api_Engine 1 /api                                                                                GET       Read
resource c cog Api_Engine 1 /user/{user}/api                                                                    Api                '{"tag":"#api","description":"apis"}'
  method c cog Api_Engine 1 /user/{user}/api                                                                    POST      Create
  method c cog Api_Engine 1 /user/{user}/api                                                                    GET       Read  
resource c cog Api_Engine 1 /user/{user}/api/{api}                                                              Api                '{"tag":"#api","description":"apis"}'
  method c cog Api_Engine 1 /user/{user}/api/{api}                                                              POST      Create
  method c cog Api_Engine 1 /user/{user}/api/{api}                                                              DELETE    Delete

resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}                                                    Version            '{"tag":"#version","description":"versioning"}'
  method c cog Api_Engine 1 /user/{user}/api/{api}/{version}                                                    GET       Read
  method c cog Api_Engine 1 /user/{user}/api/{api}/{version}                                                    UPDATE    Update
  method c cog Api_Engine 1 /user/{user}/api/{api}/{version}                                                    DELETE    Delete

#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/resource                                           Resource           '{"tag":"#view,#resource,#call,#list","description":"obtain_resources_for_version"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/resource                                           Resource           '{"tag":"#create,#resource,#call","description":"create_a_resource"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/resource/{resource}                                Resource           '{"tag":"#view,#resource,#inspect,#call","description":"obtain_details_of_specific_resource"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/resource/{resource}                                Resource           '{"tag":"#delete,#resource,#call","description":"delete_a_specific_resource"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/resource/{resource}                                Resource           '{"tag":"#modify,#resource,#call","description":"change_details_for_a_specific_resource"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/resource/{resource}/method                         Method             '{"tag":"#view,#method,#list","description":"get_methods_on_a_resource"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/resource/{resource}/method                         Method             '{"tag":"#create,#method","description":"create_a_method_on_a_resource"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/resource/{resource}/method/{method}                Method             '{"tag":"#view,#inspect,#method","description":"get_a_method_on_a_resource"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/resource/{resource}/method/{method}                Method             '{"tag":"#delete,#method","description":"delete_a_method"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/resource/{resource}/method/{method}                Method             '{"tag":"#modify,#method","description":"change_details_for_a_method"}'
#resource c cog Api_Engine 1 /user/{user}/notification                                                           Notification       '{"tag":"#user,#notify,#notification","description":"obtain_user_notifications"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/notification                                       Notification       '{"tag":"#api,#version,#notify,#notification","description":"obtain_api_notifications"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/resource/{resource}/notification                   Notification       '{"tag":"#resource,#notify,#notification","description":"obtain_resource_notifications"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/resource/{resource}/method/{method}/notification   Notification       '{"tag":"#method,#notify,#notification","description":"obtain_method_notifications"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/representation                                     Representation     '{"tag":"#list,#representation,#representations","description":"list_representations"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/representation                                     Representation     '{"tag":"#create,#representation","description":"create_a_representation"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/representation/{representation}                    Representation     '{"tag":"#view,#inspect,#representation","description":"obtain_representation_details"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/representation/{representation}                    Representation     '{"tag":"#modify,#representation","description":"modify_a_representation"}'
#resource c cog Api_Engine 1 /user/{user}/api/{api}/{version}/representation/{representation}                    Representation     '{"tag":"#delete,#representation","description":"delete_a_representation"}'

# METHODS

# TODO: Multiple methods per resource.
