#!/bin/sh -euf

indirects() {
    local model
    local out
    local type
    local len
    local i
    local el
    local val
    local found
    local actual
    local result

    model=$1
    actual=$2
    out="${CRUSTY_GEN}/${CRUSTY_CMD}_$$__${model}.out"

    if [ "${model}" = "resource" ]; then
        # FIX gonna need to tidy this and parameterise big time
        resource r ${_user_} ${_api_} ${_version_} > ${out}
        type=`jshon -t < ${out}`
        len=`jshon -l < ${out}`
        i=0; found=-1
        while [ "${i}" != "${len}" ]; do
            el=`jshon -e ${i} < ${out}`
            val=`echo ${el} | jshon -e resource | sed 's+"++g'`
            if [ "${val}" = "${actual}" ]; then
                if [ "${found}" != "-1" ]; then
                    bomb_fail "duplicate key ${actual} for model ${model}"
                fi
                found=${i}
                result=`echo ${el} | jshon -e id | sed 's+"++g'`
            fi
            math_inc "i"
        done
        if [ "${found}" = "-1" ]; then
             bomb_fail "key ${actual} not found for model ${model}"
        fi
    else
        bomb_fail "indirect for ${k} not supported"
    fi
    __=${result}
}
