#!/bin/sh -e

api r cog
version r cog Api_Engine 1
resource r cog Api_Engine 1 1
resource r cog Api_Engine 1 2
resource r cog Api_Engine 1 3
resource r cog Api_Engine 1 4
resource r cog Api_Engine 1 5
resource r cog Api_Engine 1 6
resource r cog Api_Engine 1 7
resource r cog Api_Engine 1 8
resource r cog Api_Engine 1 9
resource r cog Api_Engine 1 10
resource r cog Api_Engine 1 11
resource r cog Api_Engine 1 12
resource r cog Api_Engine 1 13
resource r cog Api_Engine 1 14
resource r cog Api_Engine 1 15
resource r cog Api_Engine 1 16
resource r cog Api_Engine 1 17
resource r cog Api_Engine 1 18
resource r cog Api_Engine 1 19
resource r cog Api_Engine 1 20
resource r cog Api_Engine 1 21
