#!/bin/sh

if [ "${AE_METHOD}" = "POST" ]; then
    __user=$1
    __api=$2
    __private=$3
    AE_REQUEST="{'name':|${__api}|,'private':|$__private|}"
    # overwriting is a hack ... table driven
    AE_RESOURCE=user/$__user/api
fi

# FIX: move off to utility area.
AE_REQUEST=`echo $AE_REQUEST | sed s'+'\''+\"+g' | sed s'+|+\"+g'`
