#!/bin/sh

set -e

CRUSTY_HOME=$HOME/.crusty
CRUSTY_DEPS=$CRUSTY_HOME/.deps

[ ! -f $CRUSTY_HOME ] && echo "creating $CRUSTY_HOME" && mkdir -p $CRUSTY_HOME

if [ ! -f $CRUSTY_DEPS/jansson ]; then
    echo "installing jansson..."
    mkdir -p $CRUSTY_DEPS; cd $CRUSTY_DEPS
    curl http://www.digip.org/jansson/releases/jansson-2.3.1.tar.gz | tar zx-
    ln -s jansson* jansson
    cd jansson
    ./configure
    make
fi

if [ ! -f $CRUSTY_DEPS/jshon ]; then
    echo "installing jshon..."
    mkdir -p $CRUSTY_DEPS; cd $CRUSTY_DEPS
    curl http://kmkeen.com/jshon/jshon.tar.gz |  tar zxf -
    cd jshon
    export C_INCLUDE_PATH=$CRUSTY_DEPS/jansson/src
    export LIBRARY_PATH=$CRUSTY_DEPS/jansson/src/.libs
    make
fi

if [ ! -f $CRUSTY_HOME/config ]; then
    echo "installing config..."
    echo "CRUSTY_PORT=80" >> $CRUSTY_HOME/config
    echo "CRUSTY_HOST=localhost" >> $CRUSTY_HOME/config
fi

echo; echo; echo; echo; echo
echo 'BRILLIANT!'
echo
echo 'now add the following lines to your ~/.profile or equivalent:'
echo
[ "`uname -s`" = "Darwin" ] && sprinkle=DY
echo '    export CRUSTY_HOME='${CRUSTY_HOME}
echo '    export PATH=$CRUSTY_HOME/.deps/jshon:$PATH'
echo '    export '$sprinkle'LD_LIBRARY_PATH=$CRUSTY_HOME/.deps/jansson/src/.libs'
echo
echo 'then check jshon runs:'
echo
echo '    echo '\''{"msg":"rockin"}'\'' | jshon -e msg'
echo
echo 'time to move on to CONFIGURATION...'
