#!/bin/sh

fail() {
    echo $1
    exit 1
}

leave() {
    echo $1
    exit 0
}

usage() {
    local msg=$1
    echo "usage: `basename $0` ${msg}"
    exit 1
}

check_args() {
    local actual=$1
    local required=$2
    local msg=$3

    [ ${actual} == ${required} ] || usage "${msg}"
}
