#!/bin/sh -euf

_status() {
  status r \
    | k "$.status" \
    | s
}

_user_list() {
  user r \
    | k "$.[*].username" \
    | s
}

_user_create() {
  local username=$1
  local email=$2
  local password=$3

  user c                 \
      ${username}        \
      ${email}           \
      ${password}        \
    | k "$.username"     \
    | s
}

_user_show() {
  local username=$1

  user r ${username} \
    | n
}

_login() {
  local username=$1
  local password=$2
  
  session c ${username} ${password} \
    | k "$.id" \
    | s
}
