#!/bin/sh -euf

_status() {
  status r
}

_user() {
  local username=$1
  local email=$2
  local password=$3

  user c                 \
      ${username}        \
      ${email}           \
      ${password}        \
    | k "$.username"     \
    | s
}


status r


# TODO modify some account yumminess...

api c                  \
  github IssueComments \
  false                \
  '{"version":{"baseurl":"http://developer.github.com/","label":"v3","index":"3"}}' \
  | k "$.name"         \
  | s

resource c                                       \
  github                                         \
  IssueComments                                  \
  1                                              \
  /repos/{owner}/{repo}/issues/{number}/comments \
  Comments \
  '{"tag":"#comments","description":"List_comments_on_an_issue"}'

method c                                         \
  github                                         \
  IssueComments                                  \
  1                                              \
  /repos/{owner}/{repo}/issues/{number}/comments \
  GET                                            \
  Read                                           \
  '{"description":"___NOT_SET___"}'

resbody u \
  github                                         \
  IssueComments                                  \
  1                                              \
  /repos/{owner}/{repo}/issues/{number}/comments \
  GET                                            \
  Read                                           \
  @body
