#!/bin/sh -euf

_status() {
  status r \
    | k "$.status" \
    | s
}

_user() {
  local username=$1
  local email=$2
  local password=$3

  user c                 \
      ${username}        \
      ${email}           \
      ${password}        \
    | k "$.username"     \
    | s
}
