#!/bin/sh -euf

status r

user c                 \
    github             \
    dudlets@github.com \
    gitfarked          \
  | k "$.username"     \
  | s

# TODO modify some account yumminess...

api c                  \
  github IssueComments \
  false                \
  '{"version":{"baseurl":"http://developer.github.com/","label":"v3","index":"3"}}' \
  | k "$.name"         \
  | s

resource c                                       \
  github                                         \
  IssueComments                                  \
  1                                              \
  /repos/{owner}/{repo}/issues/{number}/comments \
  Comments \
  '{"tag":"#comments","description":"List_comments_on_an_issue"}'

method c                                         \
  github                                         \
  IssueComments                                  \
  1                                              \
  /repos/{owner}/{repo}/issues/{number}/comments \
  GET                                            \
  Read                                           \
  '{"description":"___NOT_SET___"}'

resbody u \
  github                                         \
  IssueComments                                  \
  1                                              \
  /repos/{owner}/{repo}/issues/{number}/comments \
  GET                                            \
  Read                                           \
  @body
