#!/bin/sh -euf

  status r

 session c github gitfarked

  method d github IssueComments 1 /repos/{owner}/{repo}/issues/{number}/comments GET
resource d github IssueComments 1 /repos/{owner}/{repo}/issues/{number}/comments

 version d github IssueComments 1
     api d github IssueComments

 account d github \
   | k "$.errors" \
   | s

    user r github
