#!/bin/sh -euf

indirects() {
    model=$1
    actual=$2

    if [ "${model}" = "resource" ]; then
        indirection ${model} ${actual} 'resource r ${_user_} ${_api_} ${_version_}'
    else
        bomb_fail "indirect for ${k} not supported"
    fi
}
