#!/bin/sh

auth_checks() {
    authable; local authable=$__

    if [ ${authable} = "true" ]; then
echo "______1"
        json_v ${__response} "auth"; local auth=$__
echo "______2"
    
        if [ "$auth" = "true" ]; then
echo "______3"
            json_v "${__response}" "csrf"; local csrf=$__
            json_v "${__response}"   "id"; local   id=$__
            local r="{}"
            json_add ${r}   "id"   ${id}; local r=$__
            json_add ${r} "csrf" ${csrf}; local r=$__
            > ${AE_SESSION} echo $__
            echo "authenticated."
        else
            session_invalidate
        fi
    fi
}
    
authable() {
    if [ "${__auth}" = "*" ]; then
        __="true"
    else
        __="false"
    fi
}
