#!/bin/sh

# FIX split into core bomb and domain bomb
bomb_usage() {
    __1=$1; shift

    echo "$__1 : usage : ${AE_CMD} {c,r,u,d} $*"
    exit 1
}

bomb_fail() {
    echo error: $@
    exit 2
}

bomb_cmdfail() {
    bomb_fail "${AE_CMD}:" "$1"
}

bomb_retok() {
    if [ $1 != 0 ]; then
        fail "$2 command failed."
    fi
}
