#!/bin/sh

if [ -z ${AE_CURL} ]; then
    echo "Set AE_CURL as path to apiengine-server/"
    exit 1
fi

AE_CRUD=$1
AE_CMD=${cmd}

AE_GEN=${AE_CURL}/gen
AE_CF=${AE_GEN}/cookies
AE_HOST=localhost
AE_PORT=3000

AE_RESPONSE=${AE_GEN}/${AE_CMD}_$$.out
AE_HTTPCODE=${AE_GEN}/${AE_CMD}_$$_httpcode.out
AE_HTTPCODE=${AE_GEN}/${AE_CMD}_$$_httpcode.out
AE_SESSION=${AE_GEN}/session
AE_COLLAPSED=${AE_GEN}/collapsed
AE_FILTERED=${AE_GEN}/filtered

http_method ${AE_CRUD}; AE_METHOD=$__

if [ -f ${HOME}/.ae/config ]; then
    . ${HOME}/.ae/config
fi 

mkdir -p ${AE_GEN}
