#!/bin/sh

if [ -z ${AE_CURL} ]; then
    echo "Set AE_CURL as path to apiengine-server/"
    exit 1
fi

AE_CRUD=$1
AE_CMD=${cmd}

AE_GEN=${AE_CURL}/gen
AE_CF=${AE_GEN}/cookies
AE_HOST=localhost
AE_PORT=3000

AE_RESOURCE=${AE_CMD}
AE_RESPONSE=${AE_GEN}/${AE_RESOURCE}_$$.out
AE_HTTPCODE=${AE_GEN}/${AE_RESOURCE}_$$_httpcode.out
AE_HTTPCODE=${AE_GEN}/${AE_RESOURCE}_$$_httpcode.out
AE_SESSION=${AE_GEN}/session
AE_COLLAPSED=${AE_GEN}/collapsed
AE_FILTERED=${AE_GEN}/filtered

http_method ${AE_CRUD}; AE_METHOD=$__

if [ -f ${HOME}/.ae/config ]; then
    . ${HOME}/.ae/config
fi 

mkdir -p ${AE_GEN}

# FIX: reinstate if we go with version 2
#if [ ! -f _${AE_CMD} ]; then
#    fail "non-existent pre script: _${AE_CMD}"
#fi
#if [ ! -f %${AE_CMD} ]; then
#    fail "non-existent post script: %${AE_CMD}"
#fi
