#!/bin/sh

http_method() {
    local crud=$1
      if [ "${crud}" = "c" ];      then __="POST"
    elif [ "${crud}" = "r" ];      then __="GET"
    elif [ "${crud}" = "u" ];      then __="PUT"
    elif [ "${crud}" = "d" ];      then __="DELETE"
    elif [ "${crud}" = "GET" ];    then __=${crud}
    elif [ "${crud}" = "POST" ];   then __=${crud}
    elif [ "${crud}" = "PUT" ];    then __=${crud}
    elif [ "${crud}" = "DELETE" ]; then __=${crud}
    else
        bomb_usage "illegal crud method" "[args...]"
    fi
}

http_payload() {
    > ${AE_RESPONSE} echo '{"error":"seems there was no return value!"}'

    if [ "${AE_METHOD}" = "POST" -o "${AE_METHOD}" = "PUT" ]; then
        AE_POST="-d ${__payload}"
    fi
}

http_code() {
    local code=`cat ${AE_HTTPCODE}`

    if [ "${code}" = "000" ]; then
        bomb_fail "looks like the server is not up... : ${code} : ${AE_RESPONSE}"
    fi

    if [ "${code}" = "500" ]; then
        bomb_fail "looks like an internal server error ... : ${code} : ${AE_RESPONSE}"
    fi

    string_startswith "${code}" "4"
    if [ "$__" = "true" ]; then
        bomb_fail "${code} : ${AE_RESPONSE}"
    fi

    if [ "${code}" != "${__code}" ]; then
        bomb_fail "got ${code} expected ${__code} : ${AE_RESPONSE}"
    fi
}
