#!/bin/sh

http_method() {
    local crud=$1
      if [ "${crud}" = "c" ];      then __="POST"
    elif [ "${crud}" = "r" ];      then __="GET"
    elif [ "${crud}" = "u" ];      then __="PUT"
    elif [ "${crud}" = "d" ];      then __="DELETE"
    elif [ "${crud}" = "GET" ];    then __=${crud}
    elif [ "${crud}" = "POST" ];   then __=${crud}
    elif [ "${crud}" = "PUT" ];    then __=${crud}
    elif [ "${crud}" = "DELETE" ]; then __=${crud}
    else
        bomb_usage "illegal crud method" "[args...]"
    fi
}
