#!/bin/sh

line_available() {
    _lines=`wc -l ${AE_COLLAPSED} | cut -c7-8`
    if [ ${_lines} = 0 ]; then
        bomb_fail "no entries for [${AE_CMD}]"
    fi
}

line_locate() {
    line_available
    _line="__not_found__"
    while read _l; do
        specs_split $_l
        if [ "${__method}" = "${AE_CRUD}" ]; then 
            param_build "__args" ${__args}
            line_cmdline_match "__args"
            if [ "$__" = "true" ]; then
                if [ "${_line}" != "__not_found__" ]; then
                    bomb_fail "only one matching line allowed"
                fi
                _line=$_l
            fi
        fi        
    done < ${AE_COLLAPSED}
    if [ "${_line}" == "__not_found__" ]; then
        bomb_fail "no entry for [${AE_CMD} ${AE_CRUD}]"
    fi
    specs_split ${_line}
    param_build "__args" ${__args}
}


# FIX robably lives somewhere else
line_cmdline_match() {
    array_len "__args_m"; _alen=$__
    array_len "__cmdline"; _clen=$__
    if [ ${_clen} != 0 ]; then
        array_last "__cmdline"
        json_is "$__"
        if [ "$__" = "true" ]; then
            math_inc "_alen"    
        fi
    fi
    if [ ${_alen} = ${_clen} ]; then
        __="true"
    else
        __="false"
    fi
}
