#!/bin/sh

line_available() {
    _lines=`wc -l ${AE_COLLAPSED} | cut -c7-8`
    if [ ${_lines} = 0 ]; then
        bomb_fail "no entries for command ${AE_CMD}"
    fi
}

line_locate() {
    _line="__not_found__"
    while read __
    do
        specs_split $__
        if [ "${_method}" = "${AE_CRUD}" ]; then 
            _line=$__
        fi        
    done < ${AE_COLLAPSED}
    specs_split ${_line}
}
