#!/bin/sh

line_available() {
    _lines=`wc -l ${AE_COLLAPSED} | cut -c7-8`
    if [ ${_lines} = 0 ]; then
        bomb_fail "no entries for [${AE_CMD}]"
    fi
}

line_locate() {
    _line="__not_found__"
    while read __
    do
        specs_split $__
        if [ "${_method}" = "${AE_CRUD}" ]; then 
            params_build "_args" ${_args}
            params_match $# "_args"
            __="true" # REMOVE
            if [ "$__" = "true" ]; then
                if [ "${_line}" != "__not_found__" ]; then
                    bomb_fail "only one matching line allowed"
                fi
                _line=$__
            fi
        fi        
    done < ${AE_COLLAPSED}
    if [ "${_line}" == "__not_found__" ]; then
        bomb_fail "no entry for [${AE_CMD} ${AE_CRUD}]"
    fi
}
