#!/bin/sh

loc=`dirname $0`
cmd=`basename $0`

cd $loc

. :bomb
. :val
. :array
. :math
. :string
. :http
. :json
. :specs
. :param
. :line
. :common $*
. ^filter
. ^collapse

shift

. ^cmdline

line_locate

echo LINE: ${_line}
