#!/bin/sh

loc=`dirname $0`
cmd=`basename $0`

cd $loc

. :bomb
. :val
. :array
. :math
. :string
. :http
. :json
. :specs
. :param
. :line
. :req
. :url
. :util
. :hooks
. :session
. :auth
. :response
. :common $*
. ^filter
. ^collapse

shift

. ^cmdline

hooks_pre ${AE_CMD} $*

line_locate
 req_build
 url_build

http_payload
. ^cookie
. ^session

#echo LINE: ${__line}
#echo PAYLOAD: ${__payload}
#echo URL: ${__url}

> ${AE_HTTPCODE} curl                      \
    ${AE_COOKIES}                          \
    ${AE_CSRF}                             \
    -s                                     \
    -X ${AE_METHOD}                        \
    ${AE_POST}                             \
    -o ${AE_RESPONSE}                      \
    -w %{http_code}                        \
    ${AE_HOST}:${AE_PORT}/${AE_RESOURCE}

# FIX move out
response_get
json_pretty \"${__response}\"

http_code
hooks_post ${AE_CMD} $*
auth_checks
