#!/bin/sh

loc=`dirname $0`
cmd=`basename $0`

cd $loc

. :bomb
. :string
. :http
. :specs
. :params
. :line
. :common $*
. ^filter
. ^collapse

shift

. ^cmdline
echo CMD#: $_n
echo 'ARG[3]#': $_3
exit 5

#n=4
#eval v='$'${n}''
#echo V=$v
#string_startswith "{" "{hi there}"
#echo CONTAINS: $__
#exit 5

line_locate
#specs_split ${_line}
#arams_get "_args" ${_args}
#arams_match $# ${_args_m} ${_args_o}
echo COUNT: $#
echo LINE: ${_line}
echo MANDATORY: ${_args_m}
