#!/bin/sh

params_build() {
    _pre=$1
    shift
    _params=$@

    m=0
    o=0
    for w in ${_params}
    do
        (echo $w | grep -q "\*")
        _optional=$?
        if [ $_optional = 0 ]; then
            eval ${_pre}_o_$i='"$w"'
            o=`expr $o + 1`
        else
            eval ${_pre}_m_$i='"$w"'
            m=`expr $m + 1`
        fi
        eval ${_pre}_o='"$o"'
        eval ${_pre}_m='"$m"'
    done
}

param_get() {
    eval __='${'$1_$2'}'
}

param_last() {
    eval n='${'$1_n'}'
    if [ $n = 0 ]; then
        bomb_fail "cannot get last argument when none exists"
    fi
    i=`expr $n - 1`
    param_get $1 $i
}

params_match() {
    echo $__n
    param_last "_cmdline"



    echo $__
bomb_fail "WORKING IN HERE $#"
    if [ $1 != $2 ]; then
        bomb_fail "incorrect parameter count: expected $2, provided $1"
    fi
}
