#!/bin/sh

# FIX use array_* and value_*
param_build() {
    # $1 array name prefix
    _pre=$1
    shift
    # $@ parameters
    _params=$@

    array_create ${_pre}_m
    array_create ${_pre}_o
    for w in ${_params}
    do
        (echo $w | grep -q "\*")
        _optional=$?
        if [ $_optional = 0 ]; then
            array_append ${_pre}_o "$w"
        else
            array_append ${_pre}_m "$w"
        fi
    done
}
