#!/bin/sh

# FIX use array_* and value_*
param_build() {
    _pre=$1
    shift
    _params=$@

    m=0
    o=0
    val_poke ${_pre}_o_n 0
    val_poke ${_pre}_m_n 0
    for w in ${_params}
    do
        (echo $w | grep -q "\*")
        _optional=$?
        if [ $_optional = 0 ]; then
            # FIX rewrite these as array_expand
            val_poke ${_pre}_o_$o "$w"
            o=`expr $o + 1`
        else
            val_poke ${_pre}_m_$m "$w"
            m=`expr $m + 1`
        fi
        val_poke ${_pre}_o_n "$o"
        val_poke ${_pre}_m_n "$m"
    done
}
