#!/bin/sh

params_get() {
    _pre=$1
    shift
    _params=$@

    m=0
    o=0
    for w in ${_params}
    do
        (echo $w | grep -q "\*")
        _optional=$?
        if [ $_optional = 0 ]; then
            eval ${_pre}_o_$i='"$w"'
            o=`expr $o + 1`
        else
            eval ${_pre}_m_$i='"$w"'
            m=`expr $m + 1`
        fi
        eval ${_pre}_o='"$o"'
        eval ${_pre}_m='"$m"'
    done
}

# FIX: check this is actually needed.
params_cmdline_total() {
    if [ $2 = 0 ]; then
        __=$1
    else
        __=`expr $1 + 1`
    fi
}
