#!/bin/sh

req_build() {
    req_build_mandatory; _mandatory=$__
    req_build_optional; _optional=$__
    json_merge ${_mandatory} ${_optional}
    _payload=$__
}

req_build_mandatory() {
    i=0
    _json="{}"
    array_len "_args_m"; len=$__
    while [ "$i" != "${len}" ]; do
        array_get "_args_m" $i; _k=$__
        array_get "_cmdline" $i;_v=$__
        __=${_json}
        json_add "$_k" "$_v"
        _json=$__
        math_inc "i"
    done
    __=${_json}
}

req_build_optional() {
    # FIX the follow should be encapsulated in :param
    array_last "_cmdline"; _json=$__
    json_is "$__"
    if [ "$__" = "true" ]; then
        __=${_json}
    else
        __="{}"
    fi
    # FIX validate each optional field
}
