#!/bin/sh

req_build() {
    req_mandatory; _mandatory=$__
    req_optional; _optional=$__
    json_merge ${_mandatory} ${_optional}
    __payload=$__
}

req_mandatory() {
    i=0
    _json="{}"
    array_len "__args_m"; len=$__
    while [ "$i" != "${len}" ]; do
        array_get "__args_m" $i; _k=$__
        array_get "__cmdline" $i; _v=$__
        json_add "${_json}" "$_k" "$_v"
        _json=$__
        math_inc "i"
    done
    __=${_json}
}

req_optional() {
    # FIX the follow should be encapsulated in :param
    array_last "__cmdline"; _json=$__
    json_is "${_json}"
    if [ "$__" = "true" ]; then
        __=${_json}
    else
        __="{}"
    fi
    # FIX validate each optional field
}
