#!/bin/sh

specs_split() {
    _response=`echo $@ | cut -d: -f2`
    _location=`echo $@ | cut -d: -f3`
    _auth=`    echo $@ | cut -d: -f4`
    _error=`   echo $@ | cut -d: -f5`
    _code=`    echo $@ | cut -d: -f6`
    _cmd=`     echo $@ | cut -d: -f7`
    _method=`  echo $@ | cut -d: -f8`
    _args=`    echo $@ | cut -d: -f9`
    _url=`     echo $@ | cut -d: -f10`
}

specs_show() {
    echo "_response: $_response"
    echo "_location: $_location"
    echo "_auth    : $_auth"
    echo "_error   : $_error"
    echo "_code    : $_code"
    echo "_cmd     : $_cmd"
    echo "_method  : $_method"
    echo "_args    : $_args"
    echo "_url     : $_url"
}
