#!/bin/sh

string_startswith() {
    (echo $2 | grep -q "^$1")
    if [ $? = 0 ]; then
        __="true"
    else
        __="false"
    fi
}

string_contains() {
    (echo $2 | grep -q "$1")
    if [ $? = 0 ]; then
        __="true"
    else
        __="false"
    fi
}
