#!/bin/sh

string_startswith() {
    (echo $1 | grep -q "^$2")
    if [ $? = 0 ]; then
        __="true"
    else
        __="false"
    fi
}

string_endswith() {
    (echo $1 | grep -q "$2$")
    if [ $? = 0 ]; then
        __="true"
    else
        __="false"
    fi
}

string_contains() {
    (echo $1 | grep -q "$2")
    if [ $? = 0 ]; then
        __="true"
    else
        __="false"
    fi
}
