#!/bin/sh

url_build() {
    url_injectable ${__url}; _injectable=$__
    url_parameters

echo "1"
echo "INJECTABLE: ${_injectable}"
    eval __url=${_injectable}
echo "2"
}

url_injectable() {
    __=`echo $1 | sed 's,/#\([^/]*\),/${_\1_},g'`
}

url_parameters() {
    array_len "__args__m"; local len=$__
    local i=0
    while [ ${i} != ${len} ]; do
        array_get "__args__m" $i; local name=$__
        array_get "__cmdline" $i; local val=$__
        eval _${name}_=${val} 
        math_inc "i"
    done
}
