#!/bin/sh

url_build() {
    url_injectable ${__url}; _injectable=$__
    url_parameters
    eval __url=${_injectable}
}

url_injectable() {
    # $1 url
    __=`echo $1                                        | \
    sed -e 's+^\(.*\)#\(.*\)$+\1${_\2_}+'              | \
    sed -e 's+^\(.*\)#\([^/]*\)/\(.*\)$+\1${_\2_}/\3+' | \
    sed -e 's+^\(.*\)#\([^/]*\)/\(.*\)$+\1${_\2_}/\3+' | \
    sed -e 's+^\(.*\)#\([^/]*\)/\(.*\)$+\1${_\2_}/\3+' | \
    sed -e 's+^\(.*\)#\([^/]*\)/\(.*\)$+\1${_\2_}/\3+' | \
    sed -e 's+^\(.*\)#\([^/]*\)/\(.*\)$+\1${_\2_}/\3+' | \
    sed -e 's+^\(.*\)#\([^/]*\)/\(.*\)$+\1${_\2_}/\3+' | \
    sed -e 's+^\(.*\)#\([^/]*\)/\(.*\)$+\1${_\2_}/\3+' | \
    sed -e 's+^\(.*\)#\([^/]*\)/\(.*\)$+\1${_\2_}/\3+' | \
    sed -e 's+^\(.*\)#\([^/]*\)/\(.*\)$+\1${_\2_}/\3+' | \
    sed -e 's+^\(.*\)#\([^/]*\)/\(.*\)$+\1${_\2_}/\3+' | \
    cat`
}

url_parameters() {
    array_len "__args__m"; local len=$__
    local i=0
    while [ ${i} != ${len} ]; do
        array_get "__args__m" $i; local name=$__
        array_get "__cmdline" $i; local val=$__
        eval _${name}_=${val} 
        math_inc "i"
    done
}
