#!/bin/sh

# FIX delegate to :param_set
# FIX needs to closely follow the hairy chested array pattern
i=0
while [ $i != $# ]; do
    n=`expr $i + 1`
    eval _cmdline_$i='$'$n
    i=$n
done
_cmdline_n=$i
