#!/bin/sh

_v=`< ${AE_COLLAPSED} cat | head -7 | tail -1`
_response=`echo $_v | cut -d: -f2`
_location=`echo $_v | cut -d: -f3`
_auth=`    echo $_v | cut -d: -f4`
_error=`   echo $_v | cut -d: -f5`
_code=`    echo $_v | cut -d: -f6`
_cmd=`     echo $_v | cut -d: -f7`
_method=`  echo $_v | cut -d: -f8`
_args=`    echo $_v | cut -d: -f9`
_url=`     echo $_v | cut -d: -f10`

echo "_response: $_response"
echo "_location: $_location"
echo "_auth    : $_auth"
echo "_error   : $_error"
echo "_code    : $_code"
echo "_cmd     : $_cmd"
echo "_method  : $_method"
echo "_args    : $_args"
echo "_url     : $_url"
