#!/bin/sh

if [ "${AE_METHOD}" = "DELETE" ]; then
    if [ ! -f ${AE_SESSION} ]; then
        bomb_fail "no active session to delete."
    fi
    __=`< ${AE_SESSION} cat`
    json_v $__ "id"
    util_urlencode $__
    _session_=$__
fi

